const routes = [
  {path: '/', component: () => import(`../app/components/home.vue`)},
  {
    path: '/check_user_email',
    component: () => import(`../app/components/auth/email/checkUserEmail.vue`),
  },
  {
    path: '/email_auth_recover_password',
    component: () => import(`../app/components/auth/email/emailAuthRecoverPassword.vue`),
  },
  {path: '/users', component: () => import(`../app/components/users/index.vue`)},
  {path: '/users/:id', component: () => import(`../app/components/users/item.vue`), props: true},
  {path: '/profile', component: () => import(`../app/components/currentUser/profile.vue`)},
  // for codeGenerate ##routes_slot1
	{path: '/ctlg_system_state', component: () => import(`../app/components/ctlg_system_state/index.vue`), props: true},
	{path: '/ctlg_system_state/:id', component: () => import(`../app/components/ctlg_system_state/item.vue`), props: true},
	{path: '/ctlg_meeting_state', component: () => import(`../app/components/ctlg_meeting_state/index.vue`), props: true},
	{path: '/ctlg_meeting_state/:id', component: () => import(`../app/components/ctlg_meeting_state/item.vue`), props: true},
	{path: '/ctlg_digital_solution_state', component: () => import(`../app/components/ctlg_digital_solution_state/index.vue`), props: true},
	{path: '/ctlg_digital_solution_state/:id', component: () => import(`../app/components/ctlg_digital_solution_state/item.vue`), props: true},
	{path: '/ctlg_task_type', component: () => import(`../app/components/ctlg_task_type/index.vue`), props: true},
	{path: '/ctlg_task_type/:id', component: () => import(`../app/components/ctlg_task_type/item.vue`), props: true},
	{path: '/ctlg_task_state', component: () => import(`../app/components/ctlg_task_state/index.vue`), props: true},
	{path: '/ctlg_task_state/:id', component: () => import(`../app/components/ctlg_task_state/item.vue`), props: true},
	{path: '/ctlg_customer_task_state', component: () => import(`../app/components/ctlg_customer_task_state/index.vue`), props: true},
	{path: '/ctlg_customer_task_state/:id', component: () => import(`../app/components/ctlg_customer_task_state/item.vue`), props: true},
	{path: '/ctlg_work_state', component: () => import(`../app/components/ctlg_work_state/index.vue`), props: true},
	{path: '/ctlg_work_state/:id', component: () => import(`../app/components/ctlg_work_state/item.vue`), props: true},
	{path: '/ctlg_contract_state', component: () => import(`../app/components/ctlg_contract_state/index.vue`), props: true},
	{path: '/ctlg_contract_state/:id', component: () => import(`../app/components/ctlg_contract_state/item.vue`), props: true},
	{path: '/ctlg_technical_task_state', component: () => import(`../app/components/ctlg_technical_task_state/index.vue`), props: true},
	{path: '/ctlg_technical_task_state/:id', component: () => import(`../app/components/ctlg_technical_task_state/item.vue`), props: true},
	{path: '/ctlg_technical_task_work_state', component: () => import(`../app/components/ctlg_technical_task_work_state/index.vue`), props: true},
	{path: '/ctlg_technical_task_work_state/:id', component: () => import(`../app/components/ctlg_technical_task_work_state/item.vue`), props: true},
	{path: '/ctlg_completion_act_state', component: () => import(`../app/components/ctlg_completion_act_state/index.vue`), props: true},
	{path: '/ctlg_completion_act_state/:id', component: () => import(`../app/components/ctlg_completion_act_state/item.vue`), props: true},
	{path: '/ctlg_invoice_state', component: () => import(`../app/components/ctlg_invoice_state/index.vue`), props: true},
	{path: '/ctlg_invoice_state/:id', component: () => import(`../app/components/ctlg_invoice_state/item.vue`), props: true},
	{path: '/ctlg_filter', component: () => import(`../app/components/ctlg_filter/index.vue`), props: true},
	{path: '/ctlg_filter/:id', component: () => import(`../app/components/ctlg_filter/item.vue`), props: true},
	{path: '/ctlg_order_by', component: () => import(`../app/components/ctlg_order_by/index.vue`), props: true},
	{path: '/ctlg_order_by/:id', component: () => import(`../app/components/ctlg_order_by/item.vue`), props: true},
	{path: '/ctlg_development_task_state', component: () => import(`../app/components/ctlg_development_task_state/index.vue`), props: true},
	{path: '/ctlg_development_task_state/:id', component: () => import(`../app/components/ctlg_development_task_state/item.vue`), props: true},
	{path: '/ctlg_development_task_type', component: () => import(`../app/components/ctlg_development_task_type/index.vue`), props: true},
	{path: '/ctlg_development_task_type/:id', component: () => import(`../app/components/ctlg_development_task_type/item.vue`), props: true},
	{path: '/ctlg_time_state', component: () => import(`../app/components/ctlg_time_state/index.vue`), props: true},
	{path: '/ctlg_time_state/:id', component: () => import(`../app/components/ctlg_time_state/item.vue`), props: true},
	{path: '/meeting', component: () => import(`../app/components/meeting/index.vue`), props: true},
	{path: '/meeting/:id', component: () => import(`../app/components/meeting/item.vue`), props: true},
	{path: '/contract', component: () => import(`../app/components/contract/index.vue`), props: true},
	{path: '/contract/:id', component: () => import(`../app/components/contract/item.vue`), props: true},
	{path: '/technical_task', component: () => import(`../app/components/technical_task/index.vue`), props: true},
	{path: '/technical_task/:id', component: () => import(`../app/components/technical_task/item.vue`), props: true},
	{path: '/legal_entity', component: () => import(`../app/components/legal_entity/index.vue`), props: true},
	{path: '/legal_entity/:id', component: () => import(`../app/components/legal_entity/item.vue`), props: true},
	{path: '/company', component: () => import(`../app/components/company/index.vue`), props: true},
	{path: '/company/:id', component: () => import(`../app/components/company/item.vue`), props: true},
	{path: '/man', component: () => import(`../app/components/man/index.vue`), props: true},
	{path: '/man/:id', component: () => import(`../app/components/man/item.vue`), props: true},
	{path: '/system', component: () => import(`../app/components/system/index.vue`), props: true},
	{path: '/system/:id', component: () => import(`../app/components/system/item.vue`), props: true},
	{path: '/digital_solution', component: () => import(`../app/components/digital_solution/index.vue`), props: true},
	{path: '/digital_solution/:id', component: () => import(`../app/components/digital_solution/item.vue`), props: true},
	{path: '/development_task', component: () => import(`../app/components/development_task/index.vue`), props: true},
	{path: '/development_task/:id', component: () => import(`../app/components/development_task/item.vue`), props: true},
	{path: '/customer_task', component: () => import(`../app/components/customer_task/index.vue`), props: true},
	{path: '/customer_task/:id', component: () => import(`../app/components/customer_task/item.vue`), props: true},
	{path: '/task', component: () => import(`../app/components/task/index.vue`), props: true},
	{path: '/task/:id', component: () => import(`../app/components/task/item.vue`), props: true},
	{path: '/invoice', component: () => import(`../app/components/invoice/index.vue`), props: true},
	{path: '/invoice/:id', component: () => import(`../app/components/invoice/item.vue`), props: true},
	{path: '/payment', component: () => import(`../app/components/payment/index.vue`), props: true},
	{path: '/payment/:id', component: () => import(`../app/components/payment/item.vue`), props: true},
	{path: '/completion_act', component: () => import(`../app/components/completion_act/index.vue`), props: true},
	{path: '/completion_act/:id', component: () => import(`../app/components/completion_act/item.vue`), props: true},
	{path: '/sprint', component: () => import(`../app/components/sprint/index.vue`), props: true},
	{path: '/sprint/:id', component: () => import(`../app/components/sprint/item.vue`), props: true},
	{path: '/work', component: () => import(`../app/components/work/index.vue`), props: true},
	{path: '/work/:id', component: () => import(`../app/components/work/item.vue`), props: true},
	{path: '/time', component: () => import(`../app/components/time/index.vue`), props: true},
	{path: '/time/:id', component: () => import(`../app/components/time/item.vue`), props: true},
	{path: '/news_from_dima', component: () => import(`../app/components/news_from_dima/index.vue`), props: true},
	{path: '/news_from_dima/:id', component: () => import(`../app/components/news_from_dima/item.vue`), props: true},
  // Always leave this as last one,
  // but you can also remove it
  {
    path: '/:catchAll(.*)*',
    component: () => import('../app/components/error404.vue')
  }
]


export default routes
