const routes = [
  {path: '/', component: () => import(`../app/components/home.vue`)},
  {
    path: '/check_user_email',
    component: () => import(`../app/components/auth/email/checkUserEmail.vue`),
  },
  {
    path: '/email_auth_recover_password',
    component: () => import(`../app/components/auth/email/emailAuthRecoverPassword.vue`),
  },
  {path: '/users', component: () => import(`../app/components/users/index.vue`)},
  {path: '/users/:id', component: () => import(`../app/components/users/item.vue`), props: true},
  {path: '/profile', component: () => import(`../app/components/currentUser/profile.vue`)},
  // for codeGenerate ##routes_slot1
	{path: '/ctlg_electron_skill', component: () => import(`../app/components/ctlg_electron_skill/index.vue`), props: true},
	{path: '/ctlg_electron_skill/:id', component: () => import(`../app/components/ctlg_electron_skill/item.vue`), props: true},
	{path: '/ctlg_request_state', component: () => import(`../app/components/ctlg_request_state/index.vue`), props: true},
	{path: '/ctlg_request_state/:id', component: () => import(`../app/components/ctlg_request_state/item.vue`), props: true},
	{path: '/ctlg_request_priority', component: () => import(`../app/components/ctlg_request_priority/index.vue`), props: true},
	{path: '/ctlg_request_priority/:id', component: () => import(`../app/components/ctlg_request_priority/item.vue`), props: true},
	{path: '/ctlg_time_type', component: () => import(`../app/components/ctlg_time_type/index.vue`), props: true},
	{path: '/ctlg_time_type/:id', component: () => import(`../app/components/ctlg_time_type/item.vue`), props: true},
	{path: '/ctlg_digital_solution_state', component: () => import(`../app/components/ctlg_digital_solution_state/index.vue`), props: true},
	{path: '/ctlg_digital_solution_state/:id', component: () => import(`../app/components/ctlg_digital_solution_state/item.vue`), props: true},
	{path: '/ctlg_digital_solution_specialist_role', component: () => import(`../app/components/ctlg_digital_solution_specialist_role/index.vue`), props: true},
	{path: '/ctlg_digital_solution_specialist_role/:id', component: () => import(`../app/components/ctlg_digital_solution_specialist_role/item.vue`), props: true},
	{path: '/ctlg_functional_requirement_state', component: () => import(`../app/components/ctlg_functional_requirement_state/index.vue`), props: true},
	{path: '/ctlg_functional_requirement_state/:id', component: () => import(`../app/components/ctlg_functional_requirement_state/item.vue`), props: true},
	{path: '/ctlg_functional_requirement_specialist_role', component: () => import(`../app/components/ctlg_functional_requirement_specialist_role/index.vue`), props: true},
	{path: '/ctlg_functional_requirement_specialist_role/:id', component: () => import(`../app/components/ctlg_functional_requirement_specialist_role/item.vue`), props: true},
	{path: '/ctlg_task_type', component: () => import(`../app/components/ctlg_task_type/index.vue`), props: true},
	{path: '/ctlg_task_type/:id', component: () => import(`../app/components/ctlg_task_type/item.vue`), props: true},
	{path: '/ctlg_task_state', component: () => import(`../app/components/ctlg_task_state/index.vue`), props: true},
	{path: '/ctlg_task_state/:id', component: () => import(`../app/components/ctlg_task_state/item.vue`), props: true},
	{path: '/ctlg_task_role', component: () => import(`../app/components/ctlg_task_role/index.vue`), props: true},
	{path: '/ctlg_task_role/:id', component: () => import(`../app/components/ctlg_task_role/item.vue`), props: true},
	{path: '/ctlg_work_state', component: () => import(`../app/components/ctlg_work_state/index.vue`), props: true},
	{path: '/ctlg_work_state/:id', component: () => import(`../app/components/ctlg_work_state/item.vue`), props: true},
	{path: '/ctlg_bug_state', component: () => import(`../app/components/ctlg_bug_state/index.vue`), props: true},
	{path: '/ctlg_bug_state/:id', component: () => import(`../app/components/ctlg_bug_state/item.vue`), props: true},
	{path: '/ctlg_customer_task_state', component: () => import(`../app/components/ctlg_customer_task_state/index.vue`), props: true},
	{path: '/ctlg_customer_task_state/:id', component: () => import(`../app/components/ctlg_customer_task_state/item.vue`), props: true},
	{path: '/meeting', component: () => import(`../app/components/meeting/index.vue`), props: true},
	{path: '/meeting/:id', component: () => import(`../app/components/meeting/item.vue`), props: true},
	{path: '/contract', component: () => import(`../app/components/contract/index.vue`), props: true},
	{path: '/contract/:id', component: () => import(`../app/components/contract/item.vue`), props: true},
	{path: '/counterparty', component: () => import(`../app/components/counterparty/index.vue`), props: true},
	{path: '/counterparty/:id', component: () => import(`../app/components/counterparty/item.vue`), props: true},
	{path: '/company', component: () => import(`../app/components/company/index.vue`), props: true},
	{path: '/company/:id', component: () => import(`../app/components/company/item.vue`), props: true},
	{path: '/man', component: () => import(`../app/components/man/index.vue`), props: true},
	{path: '/man/:id', component: () => import(`../app/components/man/item.vue`), props: true},
	{path: '/system', component: () => import(`../app/components/system/index.vue`), props: true},
	{path: '/system/:id', component: () => import(`../app/components/system/item.vue`), props: true},
	{path: '/request', component: () => import(`../app/components/request/index.vue`), props: true},
	{path: '/request/:id', component: () => import(`../app/components/request/item.vue`), props: true},
	{path: '/digital_solution', component: () => import(`../app/components/digital_solution/index.vue`), props: true},
	{path: '/digital_solution/:id', component: () => import(`../app/components/digital_solution/item.vue`), props: true},
	{path: '/functional_requirement', component: () => import(`../app/components/functional_requirement/index.vue`), props: true},
	{path: '/functional_requirement/:id', component: () => import(`../app/components/functional_requirement/item.vue`), props: true},
	{path: '/invoice', component: () => import(`../app/components/invoice/index.vue`), props: true},
	{path: '/invoice/:id', component: () => import(`../app/components/invoice/item.vue`), props: true},
	{path: '/task', component: () => import(`../app/components/task/index.vue`), props: true},
	{path: '/task/:id', component: () => import(`../app/components/task/item.vue`), props: true},
	{path: '/work', component: () => import(`../app/components/work/index.vue`), props: true},
	{path: '/work/:id', component: () => import(`../app/components/work/item.vue`), props: true},
	{path: '/customer_task', component: () => import(`../app/components/customer_task/index.vue`), props: true},
	{path: '/customer_task/:id', component: () => import(`../app/components/customer_task/item.vue`), props: true},
	{path: '/bug', component: () => import(`../app/components/bug/index.vue`), props: true},
	{path: '/bug/:id', component: () => import(`../app/components/bug/item.vue`), props: true},
	{path: '/task_specialist_link', component: () => import(`../app/components/task_specialist_link/index.vue`), props: true},
	{path: '/task_specialist_link/:id', component: () => import(`../app/components/task_specialist_link/item.vue`), props: true},
	{path: '/system_customer_agent_link', component: () => import(`../app/components/system_customer_agent_link/index.vue`), props: true},
	{path: '/system_customer_agent_link/:id', component: () => import(`../app/components/system_customer_agent_link/item.vue`), props: true},
	{path: '/request_customer_agent_link', component: () => import(`../app/components/request_customer_agent_link/index.vue`), props: true},
	{path: '/request_customer_agent_link/:id', component: () => import(`../app/components/request_customer_agent_link/item.vue`), props: true},
	{path: '/functional_requirement_customer_agent_link', component: () => import(`../app/components/functional_requirement_customer_agent_link/index.vue`), props: true},
	{path: '/functional_requirement_customer_agent_link/:id', component: () => import(`../app/components/functional_requirement_customer_agent_link/item.vue`), props: true},
	{path: '/digital_solution_specialist_link', component: () => import(`../app/components/digital_solution_specialist_link/index.vue`), props: true},
	{path: '/digital_solution_specialist_link/:id', component: () => import(`../app/components/digital_solution_specialist_link/item.vue`), props: true},
	{path: '/functional_requirement_specialist_link', component: () => import(`../app/components/functional_requirement_specialist_link/index.vue`), props: true},
	{path: '/functional_requirement_specialist_link/:id', component: () => import(`../app/components/functional_requirement_specialist_link/item.vue`), props: true},
	{path: '/digital_solution_customer_agent_link', component: () => import(`../app/components/digital_solution_customer_agent_link/index.vue`), props: true},
	{path: '/digital_solution_customer_agent_link/:id', component: () => import(`../app/components/digital_solution_customer_agent_link/item.vue`), props: true},
	{path: '/customer_task_customer_agent_link', component: () => import(`../app/components/customer_task_customer_agent_link/index.vue`), props: true},
	{path: '/customer_task_customer_agent_link/:id', component: () => import(`../app/components/customer_task_customer_agent_link/item.vue`), props: true},
	{path: '/bug_customer_agent_link', component: () => import(`../app/components/bug_customer_agent_link/index.vue`), props: true},
	{path: '/bug_customer_agent_link/:id', component: () => import(`../app/components/bug_customer_agent_link/item.vue`), props: true},
	{path: '/work_specialist_link', component: () => import(`../app/components/work_specialist_link/index.vue`), props: true},
	{path: '/work_specialist_link/:id', component: () => import(`../app/components/work_specialist_link/item.vue`), props: true},
	{path: '/work_task_link', component: () => import(`../app/components/work_task_link/index.vue`), props: true},
	{path: '/work_task_link/:id', component: () => import(`../app/components/work_task_link/item.vue`), props: true},
	{path: '/company_man_link', component: () => import(`../app/components/company_man_link/index.vue`), props: true},
	{path: '/company_man_link/:id', component: () => import(`../app/components/company_man_link/item.vue`), props: true},
	{path: '/time', component: () => import(`../app/components/time/index.vue`), props: true},
	{path: '/time/:id', component: () => import(`../app/components/time/item.vue`), props: true},
	{path: '/comment', component: () => import(`../app/components/comment/index.vue`), props: true},
	{path: '/comment/:id', component: () => import(`../app/components/comment/item.vue`), props: true},
	{path: '/news_from_dima', component: () => import(`../app/components/news_from_dima/index.vue`), props: true},
	{path: '/news_from_dima/:id', component: () => import(`../app/components/news_from_dima/item.vue`), props: true},
  // Always leave this as last one,
  // but you can also remove it
  {
    path: '/:catchAll(.*)*',
    component: () => import('../app/components/error404.vue')
  }
]


export default routes
