docType = "FunctionalRequirementSpecialistLink"
tableComment = "связь функционального требования и специалиста"

tableName ="functional_requirement_specialist_link"

fields = [
	{name="id",			type="serial"},
	{name="functional_requirement_id",					type="int",	 comment="id функционального требования"},
	{name="specialist_id",					type="int",	 comment="специалист"},
	{name="role_id",					type="int",	 comment="роль"},
	{name="description",					type="text",	 comment="описание"},
	{name="author_id",					type="int",	 comment="автор"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="functional_requirement_id", ref="functional_requirement", fk="id"},
	{fld="specialist_id", ref="man", fk="id"},
	{fld="role_id", ref="ctlg_functional_requirement_specialist_role", fk="id"},
	{fld="author_id", ref="man", fk="id"}
]

triggers = [
	{name="functional_requirement_specialist_link_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="functional_requirement_specialist_link_trigger_before", when="before insert or update", ref="for each row", funcName="functional_requirement_specialist_link_trigger_before"},
	{name="functional_requirement_specialist_link_trigger_after", when="after insert or update", ref="for each row", funcName="functional_requirement_specialist_link_trigger_after"}
]



methods = [
	"functional_requirement_specialist_link_get_by_id",
	"functional_requirement_specialist_link_list",
	"functional_requirement_specialist_link_update",
	"functional_requirement_specialist_link_trigger_before",
	"functional_requirement_specialist_link_trigger_after"
]

alterScripts = [
	"alter table functional_requirement_specialist_link add column if not exists functional_requirement_id int;",
	"alter table functional_requirement_specialist_link add column if not exists specialist_id int;",
	"alter table functional_requirement_specialist_link add column if not exists role_id int;",
	"alter table functional_requirement_specialist_link add column if not exists description text;",
	"alter table functional_requirement_specialist_link add column if not exists author_id int;",
	"alter table functional_requirement_specialist_link add column if not exists search_text text;"
]