docType = "Message"
tableComment = "Таблица сообщений"

tableName ="message"

fields = [
    {name="id",                       type="serial"},
    {name="user_id",                  type="int", ext="not null",     comment="id пользователя"},
    {name="title",                    type="char", size=100, ext="not null",  comment="заголовок"},
    {name="data",                     type="jsonb",                   comment="текст сообщения"},
    {name="is_read_conditions",       type="jsonb",                   comment="возможные условия для смены сообщения"},
    {name="table_name",			      type="char", size=50,           comment="название таблицы, к которой сообщение"},
    {name="table_id",			      type="int",                     comment="id из таблицы"},
    {name="type",                     type="char", size=20,           comment="Тип сообщения: Error, Warning, Info"},
    {name="state",                    type="char", size=20,           comment=""},
    {name="is_read",                  type="bool", ext="not null default false",  comment="признак что сообщение прочитано пользователем"},
    {name="options",                  type="jsonb",                   comment="Разные дополнительные параметры"},
    {name="updated_at",               type="timestamp",   ext="with time zone"},
    {name="created_at",               type="timestamp",   ext="with time zone"},
    {name="deleted",                  type="bool",        ext="not null default false"},
]

fkConstraints = [
    {fld="user_id", ref="\"user\"", fk="id"},
]

triggers = [
    {name="message_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
    {name="message_event", when="after insert or update", ref="for each row", funcName="notify_event"},
]

methods = [
    "message_update",
    "message_list",
    "message_for_role",
    "message_mark_as_read",
]

alterScripts = [
    "alter table message add column if not exists is_read_conditions jsonb;",
]

