docType = "NewsFromDima"
tableComment = "новость от Димы"

tableName ="news_from_dima"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="familiarized",					type="bool", 	ext=" default false",	 comment="ознакомился"},
	{name="description",					type="text",	 comment="описание"},
	{name="file",					type="jsonb",	 comment="файлы"},
	{name="image",					type="jsonb",	 comment="картинки"},
	{name="conclusion",					type="text",	 comment="выводы"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="news_from_dima_title_already_exist", ext="UNIQUE (title)"}
]

triggers = [
	{name="news_from_dima_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="news_from_dima_trigger_before", when="before insert or update", ref="for each row", funcName="news_from_dima_trigger_before"},
	{name="news_from_dima_trigger_after", when="after insert or update", ref="for each row", funcName="news_from_dima_trigger_after"}
]



methods = [
	"news_from_dima_list",
	"news_from_dima_update",
	"news_from_dima_get_by_id",
	"news_from_dima_trigger_before",
	"news_from_dima_trigger_after"
]

alterScripts = [
	"alter table news_from_dima add column if not exists title CHARACTER VARYING(150);",
	"alter table news_from_dima add column if not exists familiarized bool;",
	"alter table news_from_dima add column if not exists description text;",
	"alter table news_from_dima add column if not exists file jsonb;",
	"alter table news_from_dima add column if not exists image jsonb;",
	"alter table news_from_dima add column if not exists conclusion text;",
	"alter table news_from_dima add column if not exists search_text text;"
]