version: '2'
services:
  app:
    build: .
    networks:
      - counter_net
    depends_on:
      - postgres

  postgres:
    image: postgres:12
#    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - postgres_data_Counter_12:/var/lib/postgresql/data
    ports:
      - "5438:5432"
    command: postgres -c shared_preload_libraries=pg_stat_statements -c pg_stat_statements.track=all -c max_connections=200
    environment:
      POSTGRES_PASSWORD: maximum777strong_password!

volumes:
  postgres_data_Counter_12:

networks:
  counter_net:
    driver: bridge
