docType = "Project"
tableComment = "проект"

tableName ="project"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="description",					type="text",	 comment="описание"},
	{name="client_id",					type="int",	 comment="заказчик"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="project_title_already_exist", ext="UNIQUE (title)"},
	{fld="client_id", ref="client", fk="id"}
]

triggers = [
	{name="project_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="project_trigger_before", when="before insert or update", ref="for each row", funcName="project_trigger_before"},
	{name="project_trigger_after", when="after insert or update", ref="for each row", funcName="project_trigger_after"}
]



methods = [
	"project_list",
	"project_update",
	"project_get_by_id",
	"project_trigger_before",
	"project_trigger_after"
]

alterScripts = [
	"alter table project add column if not exists title CHARACTER VARYING(150);",
	"alter table project add column if not exists description text;",
	"alter table project add column if not exists client_id int;",
	"alter table project add column if not exists search_text text;"
]