
docType = "TaskType"
tableComment = "Тип_Задачи"

tableName ="task_type"

fields = [
   {name="id",          type="serial" },
   {name="title",       type="char",  size=100,   ext="not null",    comment="Название" },
   {name="table_name",  type="char",  size=100,                      comment="Название таблицы, к которой прикрепляется задача" },
   {name="title_en",    type="char",  size=100,                      comment="неизменяемое название, для поиска типа задач. Заполняется программно и не изменяется через UI" },
   {name="options",     type="jsonb",       comment="Разные дополнительные параметры" },
   {name="created_at",  type="timestamp",   ext="with time zone" },
   {name="updated_at",  type="timestamp",   ext="with time zone" },
   {name="deleted",     type="bool",        ext="not null default false" },
]

triggers = [
    {name="task_type_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
    {name="task_type_change", when="before update", ref="for each row", funcName="trigger_task_type_change"},
]

methods = [
    "task_type_update",
    "task_type_list",
    "task_type_get_by_id",
]


alterScripts = [
	"alter table task_type add column if not exists title_en CHARACTER VARYING(100);",
]