docType = "Chat"
tableComment = "Чат"

tableName ="chat"

fields = [
   {name="id",              type="serial" },
   {name="title",           type="char", size=100,      comment="заголовок"},
   {name="table_name",      type="char",  size=70,      comment="Название таблицы" },
   {name="table_id",        type="int",                 comment="id в таблице. Запрет на изменение. Проверка в триггере." },
   {name="table_options",   type="jsonb",               comment="данные из таблицы (title и пр). Запрет на изменения. Проверка в триггере." },
   {name="options",         type="jsonb",               comment="Разные дополнительные параметры" },
   {name="created_at",      type="timestamp",           ext="with time zone" },
   {name="updated_at",      type="timestamp",           ext="with time zone" },
   {name="deleted",         type="bool",                ext="not null default false" },
   
]

triggers = [
    {name="chat_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
    {name="chat_update_table_name", when="before insert or update", ref="for each row", funcName="trigger_chat_update_table_name"},
]

methods = [
    "chat_update",
    "chat_get_by_id",
    "chat_for_table_id",
]