docType = "Time"
tableComment = "время"

tableName ="time"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="minute",					type="int",	 comment="кол-во минут"},
	{name="specialist_id",					type="int",	 comment="специалист"},
	{name="task_id",					type="int",	 comment="задача"},
	{name="type_id",					type="int",	 comment="тип времени"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="time_title_already_exist", ext="UNIQUE (title)"},
	{fld="specialist_id", ref="employee", fk="id"},
	{fld="task_id", ref="task", fk="id"},
	{fld="type_id", ref="ctlg_time_type", fk="id"}
]

triggers = [
	{name="time_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="time_trigger_before", when="before insert or update", ref="for each row", funcName="time_trigger_before"},
	{name="time_trigger_after", when="after insert or update", ref="for each row", funcName="time_trigger_after"}
]



methods = [
	"time_list",
	"time_update",
	"time_get_by_id",
	"time_trigger_before",
	"time_trigger_after"
]

alterScripts = [
	"alter table time add column if not exists title CHARACTER VARYING(150);",
	"alter table time add column if not exists minute int;",
	"alter table time add column if not exists specialist_id int;",
	"alter table time add column if not exists task_id int;",
	"alter table time add column if not exists type_id int;",
	"alter table time add column if not exists search_text text;"
]