docType = "Man"
tableComment = "человек"

tableName ="man"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="last_name",					type="char",	size=30,	 comment="фамилия"},
	{name="name",					type="char",	size=30,	 comment="имя"},
	{name="middle_name",					type="char",	size=30,	 comment="отчество"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="man_title_already_exist", ext="UNIQUE (title)"}
]

triggers = [
	{name="man_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="man_trigger_before", when="before insert or update", ref="for each row", funcName="man_trigger_before"},
	{name="man_trigger_after", when="after insert or update", ref="for each row", funcName="man_trigger_after"}
]



methods = [
	"man_get_by_id",
	"man_list",
	"man_update",
	"man_trigger_before",
	"man_trigger_after"
]

alterScripts = [
	"alter table man add column if not exists title CHARACTER VARYING(150);",
	"alter table man add column if not exists last_name CHARACTER VARYING(30);",
	"alter table man add column if not exists name CHARACTER VARYING(30);",
	"alter table man add column if not exists middle_name CHARACTER VARYING(30);",
	"alter table man add column if not exists search_text text;"
]