export default {
  appName: 'Electron',
  uiAppName: 'Electron',
  apiUrl: () => process.env.NODE_ENV === 'development' ? 'http://localhost:3091' : 'https://system.i-electron.ru',
  wsUrl: () => process.env.NODE_ENV === 'development' ? 'ws://localhost:3091' : 'wss://system.i-electron.ru',
  isEmailAuth: {
    firstName: true,
    lastName: true,
  },
  logoSrc: 'image/electron_logo.png',
  dadataToken: '1cf3a086e3dbe1306ed142d2b5fbc1b324b8eb60',
  // yandexMetrikaId: 54433825,
  breadcrumbIcons: {
    employee: 'far fa-user-circle',
meeting: 'fas fa-users',
comment: 'far fa-comment-dots',
contract: 'fas fa-file-signature',
counterparty: 'far fa-handshake',
company: 'fas fa-building',
man: 'fas fa-male',
ctlg_time_type: 'fas fa-list-ul',
ctlg_request_state: 'fas fa-list-ul',
request: 'far fa-lightbulb',
functional_requirement: 'fas fa-square-root-alt',
digital_solution: 'fas fa-rocket',
sprint: 'fas fa-running',
system: 'fas fa-project-diagram',
invoice: 'fas fa-file-invoice-dollar',
ctlg_dev_task_state: 'fas fa-list-ul',
time: 'fas fa-building',
task: 'fas fa-clipboard-check'
  },
  
  tablesForTask: {},
}
