docType = "TaskSpecialistLink"
tableComment = "участник задачи"

tableName ="task_specialist_link"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="task_id",					type="int",	 comment="id задачи"},
	{name="specialist_id",					type="int",	 comment="специалист"},
	{name="role_id",					type="int",	 comment="роль"},
	{name="description",					type="text",	 comment="описание"},
	{name="author_id",					type="int",	 comment="автор"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="task_specialist_link_title_already_exist", ext="UNIQUE (title)"},
	{fld="task_id", ref="task", fk="id"},
	{fld="specialist_id", ref="man", fk="id"},
	{fld="role_id", ref="ctlg_task_role", fk="id"},
	{fld="author_id", ref="man", fk="id"}
]

triggers = [
	{name="task_specialist_link_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="task_specialist_link_trigger_before", when="before insert or update", ref="for each row", funcName="task_specialist_link_trigger_before"},
	{name="task_specialist_link_trigger_after", when="after insert or update", ref="for each row", funcName="task_specialist_link_trigger_after"}
]



methods = [
	"task_specialist_link_update",
	"task_specialist_link_get_by_id",
	"task_specialist_link_list",
	"task_specialist_link_trigger_before",
	"task_specialist_link_trigger_after"
]

alterScripts = [
	"alter table task_specialist_link add column if not exists title CHARACTER VARYING(150);",
	"alter table task_specialist_link add column if not exists task_id int;",
	"alter table task_specialist_link add column if not exists specialist_id int;",
	"alter table task_specialist_link add column if not exists role_id int;",
	"alter table task_specialist_link add column if not exists description text;",
	"alter table task_specialist_link add column if not exists author_id int;",
	"alter table task_specialist_link add column if not exists search_text text;"
]