docType = "WorkTaskLink"
tableComment = "связь дела и задачи"

tableName ="work_task_link"

fields = [
	{name="id",			type="serial"},
	{name="work_id",					type="int",	 comment="дело"},
	{name="task_id",					type="int",	 comment="задача"},
	{name="description",					type="text",	 comment="описание"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{fld="work_id", ref="work", fk="id"},
	{fld="task_id", ref="task", fk="id"},
	{name="work_task_link_already_exist", ext="UNIQUE (work_id, task_id)"},
]

triggers = [
	{name="work_task_link_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="work_task_link_trigger_before", when="before insert or update", ref="for each row", funcName="work_task_link_trigger_before"},
	{name="work_task_link_trigger_after", when="after insert or update", ref="for each row", funcName="work_task_link_trigger_after"}
]



methods = [
	"work_task_link_update",
	"work_task_link_get_by_id",
	"work_task_link_list",
	"work_task_link_trigger_before",
	"work_task_link_trigger_after"
]

alterScripts = [
	"alter table work_task_link add column if not exists work_id int;",
	"alter table work_task_link add column if not exists task_id int;",
	"alter table work_task_link add column if not exists description text;",
	"alter table work_task_link add column if not exists search_text text;"
]