docType = "WorkTimeSheet"
tableComment = "ЛУРВ"

tableName ="work_time_sheet"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="work_time_sheet_title_already_exist", ext="UNIQUE (title)"}
]

triggers = [
	{name="work_time_sheet_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="work_time_sheet_trigger_before", when="before insert or update", ref="for each row", funcName="work_time_sheet_trigger_before"},
	{name="work_time_sheet_trigger_after", when="after insert or update", ref="for each row", funcName="work_time_sheet_trigger_after"}
]



methods = [
	"work_time_sheet_get_by_id",
	"work_time_sheet_list",
	"work_time_sheet_update",
	"work_time_sheet_trigger_before",
	"work_time_sheet_trigger_after"
]

alterScripts = [
	"alter table work_time_sheet add column if not exists title CHARACTER VARYING(150);",
	"alter table work_time_sheet add column if not exists search_text text;"
]