docType = "Invoice"
tableComment = "счёт"

tableName ="invoice"

fields = [
	{name="id",			type="serial"},
	{name="title",					type="char",	size=150, 	ext="not null",	 comment="название"},
	{name="total_amount",					type="int",	 comment="сумма"},
	{name="state_id",					type="int",	 comment="статус"},
	{name="technical_task_id",					type="int",	 comment="техническое задание"},
	{name="date_plan_paid",					type="timestamp",	 comment="планируемая дата оплаты"},
	{name="date_transfer",					type="timestamp",	 comment="дата выставления"},
	{name="date_paid",					type="timestamp",	 comment="дата оплаты"},
	{name="search_text",			type="text",	comment="колонка для поиска"},
	{name="options",				type="jsonb",	comment="разные дополнительные параметры"},
	{name="created_at",				type="timestamp",	ext="with time zone"},
	{name="updated_at",				type="timestamp",	ext="with time zone"},
	{name="deleted",				type="bool",	ext="not null default false"}
]

fkConstraints = [
	{name="invoice_title_already_exist", ext="UNIQUE (title)"},
	{fld="state_id", ref="ctlg_invoice_state", fk="id"},
	{fld="technical_task_id", ref="technical_task", fk="id"}
]

triggers = [
	{name="invoice_created", when="before insert or update", ref="for each row", funcName="builtin_fld_update"},
	{name="invoice_trigger_before", when="before insert or update", ref="for each row", funcName="invoice_trigger_before"},
	{name="invoice_trigger_after", when="after insert or update", ref="for each row", funcName="invoice_trigger_after"}
]



methods = [
	"invoice_list",
	"invoice_update",
	"invoice_get_by_id",
	"invoice_trigger_before",
	"invoice_trigger_after"
]

alterScripts = [
	"alter table invoice add column if not exists title CHARACTER VARYING(150);",
	"alter table invoice add column if not exists total_amount int;",
	"alter table invoice add column if not exists state_id int;",
	"alter table invoice add column if not exists technical_task_id int;",
	"alter table invoice add column if not exists date_plan_paid timestamp;",
	"alter table invoice add column if not exists date_transfer timestamp;",
	"alter table invoice add column if not exists date_paid timestamp;",
	"alter table invoice add column if not exists search_text text;"
]